CREATE TABLE IF NOT EXISTS account
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_number VARCHAR(255),
    CONSTRAINT pk_account PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS transaction
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id     BIGINT,
    operation_type SMALLINT,
    amount         DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_transaction PRIMARY KEY (id)
);