DROP TABLE IF EXISTS account CASCADE ;
DROP TABLE IF EXISTS transaction CASCADE ;

CREATE TABLE IF NOT EXISTS account
(
    account_id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_number VARCHAR(255),
    CONSTRAINT pk_account PRIMARY KEY (account_id)
);

CREATE TABLE IF NOT EXISTS transaction
(
    transaction_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id        BIGINT,
    operation_type_id SMALLINT,
    amount            DOUBLE PRECISION                        NOT NULL,
    transaction_date  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_transaction PRIMARY KEY (transaction_id)
);

ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account (account_id);

CREATE TABLE accountv2
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    holder_name VARCHAR(255)                            NOT NULL,
    balance     DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_accountv2 PRIMARY KEY (id)
);

ALTER TABLE accountv2
    ADD CONSTRAINT uc_accountv2_holdername UNIQUE (holder_name);

-- ========================================================================
-- generate by claude.ai
-- ========================================================================
-- ======================== ACCOUNT TABLE INSERTS ========================

-- Insert sample accounts
INSERT INTO account (document_number) VALUES
                                          ('12345678900'),
                                          ('98765432100'),
                                          ('11122233344'),
                                          ('55566677788'),
                                          ('99988877766');

-- ============

-- ======================== ACCOUNT TABLE INSERTS ========================

-- Insert sample accounts
INSERT INTO account (document_number) VALUES
                                          ('12345678900'),
                                          ('98765432100'),
                                          ('11122233344'),
                                          ('55566677788'),
                                          ('99988877766');

-- ======================== TRANSACTION TABLE INSERTS ========================

-- Insert transactions for account_id = 1 (document: 12345678900)
INSERT INTO transaction (account_id, operation_type_id, amount, transaction_date) VALUES
-- Normal purchases (negative amounts)
(1, 1, -50.00, '2024-01-15 10:30:00'),
(1, 1, -23.50, '2024-01-15 14:45:00'),
(1, 1, -18.70, '2024-01-16 09:15:00'),
(1, 1, -125.30, '2024-01-17 16:20:00'),

-- Purchase with installments (negative amounts)
(1, 2, -200.00, '2024-01-18 11:30:00'),
(1, 2, -150.75, '2024-01-19 13:45:00'),

-- Withdrawals (negative amounts)
(1, 3, -100.00, '2024-01-20 08:30:00'),
(1, 3, -50.00, '2024-01-21 15:45:00'),

-- Credit vouchers (positive amounts)
(1, 4, 60.00, '2024-01-22 12:00:00'),
(1, 4, 120.50, '2024-01-23 14:30:00');

-- Insert transactions for account_id = 2 (document: 98765432100)
INSERT INTO transaction (account_id, operation_type_id, amount, transaction_date) VALUES
-- Normal purchases
(2, 1, -35.90, '2024-01-10 09:30:00'),
(2, 1, -89.50, '2024-01-11 11:15:00'),
(2, 1, -12.30, '2024-01-12 16:45:00'),

-- Withdrawals
(2, 3, -200.00, '2024-01-13 10:30:00'),
(2, 3, -150.00, '2024-01-14 14:20:00'),

-- Credit vouchers
(2, 4, 100.00, '2024-01-15 13:00:00'),
(2, 4, 75.80, '2024-01-16 15:30:00');

-- Insert transactions for account_id = 3 (document: 11122233344)
INSERT INTO transaction (account_id, operation_type_id, amount, transaction_date) VALUES
-- Mixed transactions
(3, 1, -45.20, '2024-01-08 08:00:00'),
(3, 2, -300.00, '2024-01-09 10:30:00'),
(3, 3, -80.00, '2024-01-10 12:15:00'),
(3, 4, 200.00, '2024-01-11 14:45:00'),
(3, 1, -25.50, '2024-01-12 16:30:00');

-- Insert transactions for account_id = 4 (document: 55566677788)
INSERT INTO transaction (account_id, operation_type_id, amount, transaction_date) VALUES
-- Recent transactions
(4, 1, -67.80, '2024-01-20 09:00:00'),
(4, 4, 150.00, '2024-01-21 11:30:00'),
(4, 3, -90.00, '2024-01-22 13:45:00'),
(4, 1, -33.25, '2024-01-23 15:20:00');

-- Insert transactions for account_id = 5 (document: 99988877766)
INSERT INTO transaction (account_id, operation_type_id, amount, transaction_date) VALUES
-- Single transaction for testing
(5, 4, 500.00, '2024-01-25 10:00:00');

-- ======================== BULK INSERT WITH CURRENT TIMESTAMPS ========================

-- Insert more accounts with current timestamp transactions
INSERT INTO account (document_number) VALUES
                                          ('12312312312'),
                                          ('45645645645'),
                                          ('78978978978'),
                                          ('32132132132'),
                                          ('65465465465');

-- Insert recent transactions with CURRENT_TIMESTAMP
INSERT INTO transaction (account_id, operation_type_id, amount, transaction_date) VALUES
                                                                                      (6, 1, -29.99, CURRENT_TIMESTAMP - INTERVAL '5 hours'),
                                                                                      (6, 1, -15.50, CURRENT_TIMESTAMP - INTERVAL '4 hours'),
                                                                                      (6, 4, 100.00, CURRENT_TIMESTAMP - INTERVAL '3 hours'),
                                                                                      (6, 3, -50.00, CURRENT_TIMESTAMP - INTERVAL '2 hours'),
                                                                                      (6, 1, -8.75, CURRENT_TIMESTAMP - INTERVAL '1 hour'),

                                                                                      (7, 2, -199.99, CURRENT_TIMESTAMP - INTERVAL '6 hours'),
                                                                                      (7, 4, 250.00, CURRENT_TIMESTAMP - INTERVAL '3 hours'),
                                                                                      (7, 1, -45.30, CURRENT_TIMESTAMP - INTERVAL '1 hour'),

                                                                                      (8, 3, -300.00, CURRENT_TIMESTAMP - INTERVAL '8 hours'),
                                                                                      (8, 4, 150.00, CURRENT_TIMESTAMP - INTERVAL '4 hours'),
                                                                                      (8, 1, -22.50, CURRENT_TIMESTAMP - INTERVAL '2 hours'),

                                                                                      (9, 1, -55.80, CURRENT_TIMESTAMP - INTERVAL '7 hours'),
                                                                                      (9, 1, -33.20, CURRENT_TIMESTAMP - INTERVAL '5 hours'),
                                                                                      (9, 4, 200.00, CURRENT_TIMESTAMP - INTERVAL '3 hours'),

                                                                                      (10, 4, 1000.00, CURRENT_TIMESTAMP - INTERVAL '1 day');