DROP TABLE account;

CREATE TABLE IF NOT EXISTS account
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_number VARCHAR(255),
    CONSTRAINT pk_account PRIMARY KEY (id)
);


