DROP TABLE IF EXISTS account CASCADE ;
DROP TABLE IF EXISTS transaction CASCADE ;

CREATE TABLE IF NOT EXISTS account
(
    account_id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_number VARCHAR(255),
    CONSTRAINT pk_account PRIMARY KEY (account_id)
    );

CREATE TABLE IF NOT EXISTS transaction
(
    transaction_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id        BIGINT,
    operation_type_id SMALLINT,
    amount            DOUBLE PRECISION                        NOT NULL,
    transaction_date  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_transaction PRIMARY KEY (transaction_id)
    );

ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account (account_id);
